/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Games */
        get: operations["list_games_api_v1_games_get"];
        put?: never;
        /** Create Game */
        post: operations["create_game_api_v1_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_api_v1_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}/moves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Moves */
        get: operations["list_moves_api_v1_games__game_id__moves_get"];
        put?: never;
        /** Play Move */
        post: operations["play_move_api_v1_games__game_id__moves_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/games/{game_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Game */
        post: operations["archive_game_api_v1_games__game_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BoardOut */
        BoardOut: {
            /** Index */
            index: number;
            status: components["schemas"]["BoardStatus"];
            /** Cells */
            cells: (components["schemas"]["Player"] | null)[];
        };
        /**
         * BoardStatus
         * @enum {string}
         */
        BoardStatus: "open" | "x" | "o" | "tied";
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "game_finished" | "game_archived" | "wrong_board" | "cell_occupied" | "board_already_decided" | "already_archived" | "game_not_found" | "validation_error";
        /** ErrorResponse */
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            /** Detail */
            detail: string;
        };
        /** GameDetail */
        GameDetail: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Is Archived */
            is_archived: boolean;
            /** Boards */
            boards: components["schemas"]["BoardOut"][];
            current_player: components["schemas"]["Player"];
            /** Active Board */
            active_board: number | null;
            status: components["schemas"]["GameStatus"];
            winner: components["schemas"]["Player"] | null;
            /** Move Count */
            move_count: number;
        };
        /** GameListEnvelope */
        GameListEnvelope: {
            /** Items */
            items: components["schemas"]["GameSummary"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /**
         * GameSort
         * @enum {string}
         */
        GameSort: "created_at" | "-created_at";
        /**
         * GameStatus
         * @enum {string}
         */
        GameStatus: "in_progress" | "won" | "drawn";
        /** GameSummary */
        GameSummary: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            status: components["schemas"]["GameStatus"];
            winner: components["schemas"]["Player"] | null;
            current_player: components["schemas"]["Player"];
            /** Move Count */
            move_count: number;
        };
        /**
         * MoveCreate
         * @description The player is never sent by the client; extra fields are rejected.
         */
        MoveCreate: {
            /** Board */
            board: number;
            /** Cell */
            cell: number;
        };
        /** MoveListEnvelope */
        MoveListEnvelope: {
            /** Items */
            items: components["schemas"]["MoveOut"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
        };
        /** MoveOut */
        MoveOut: {
            /** Id */
            id: number;
            /** Game Id */
            game_id: number;
            /** Board */
            board: number;
            /** Cell */
            cell: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            player: components["schemas"]["Player"];
            /** Move Number */
            move_number: number;
        };
        /**
         * Player
         * @enum {string}
         */
        Player: "x" | "o";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_games_api_v1_games_get: {
        parameters: {
            query?: {
                sort?: components["schemas"]["GameSort"];
                page?: number;
                page_size?: number;
                status?: components["schemas"]["GameStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameListEnvelope"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_game_api_v1_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
        };
    };
    get_game_api_v1_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_moves_api_v1_games__game_id__moves_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveListEnvelope"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    play_move_api_v1_games__game_id__moves_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MoveOut"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rule conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    archive_game_api_v1_games__game_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameDetail"];
                };
            };
            /** @description Game not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rule conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
